const FETCHING_LANES = 'FETCHING_LANES';
const REQUESTED_LANES = 'REQUESTED_LANES';
const ERROR_LANES = 'ERROR_LANES';

const FETCH_CARDS = 'FETCH_CARDS';
const REQUESTED_CARDS = 'REQUESTED_CARDS';
const ERROR_CARDS = 'ERROR_CARDS';

export {
    FETCHING_LANES,
    REQUESTED_LANES,
    ERROR_LANES,
    FETCH_CARDS,
    REQUESTED_CARDS,
    ERROR_CARDS
}