const FETCHING_LANES = 'FETCHING_LANES';
const REQUESTED_LANES = 'REQUESTED_LANES';
const ERROR_LANES = 'ERROR_LANES';

const FETCH_ALL_CARDS = 'FETCH_ALL_CARDS';
const REQUESTED_CARDS = 'REQUESTED_CARDS';
const ERROR_CARDS = 'ERROR_CARDS';
const CHANGE_CARD_LANE = 'CHANGE_CARD_LANE';
const REQUESTED_ALL_CARDS = 'REQUESTED_ALL_CARDS';

const ADD_NEW_CARD = 'ADD_NEW_CARD';
const ERROR_NEW_CARD = 'ERROR_NEW_CARD';
const DELETE_CARD = 'DELETE_CARD';
const EDIT_CARD = 'EDIT_CARD';
const REQUESTED_EDIT_CARDS = 'REQUESTED_EDIT_CARDS';

export {
    FETCHING_LANES,
    REQUESTED_LANES,
    ERROR_LANES,
    FETCH_ALL_CARDS,
    REQUESTED_CARDS,
    CHANGE_CARD_LANE,
    ERROR_CARDS,
    ADD_NEW_CARD,
    ERROR_NEW_CARD,
    DELETE_CARD,
    EDIT_CARD,
    REQUESTED_EDIT_CARDS,
    REQUESTED_ALL_CARDS
}