const FETCHING_LANES = 'FETCHING_LANES';
const REQUESTED_LANES = 'REQUESTED_LANES';
const ERROR_LANES = 'ERROR_LANES';

const FETCH_CARDS = 'FETCH_CARDS';
const REQUESTED_CARDS = 'REQUESTED_CARDS';
const ERROR_CARDS = 'ERROR_CARDS';
const CHANGE_CARD_LANE = 'CHANGE_CARD_LANE';

const CLOSE_MODAL = 'CLOSE_MODAL';
const OPEN_MODAL = 'OPEN_MODAL';

export {
    FETCHING_LANES,
    REQUESTED_LANES,
    ERROR_LANES,
    FETCH_CARDS,
    REQUESTED_CARDS,
    CHANGE_CARD_LANE,
    ERROR_CARDS,
    CLOSE_MODAL,
    OPEN_MODAL,
}